### ISSUE TITLE
React-router error

### ISSUE THREAD

**Issue by adharbert** [StephenGrider/ReduxSimpleStarter#234]
I'm not sure what the error is, but when I installed react-router it isn't working.   I get the same error over and over on the new site, if I remove imports for react-router I am able to see the page, but once I log back in, I get the following error:

> bundle.js:86 Uncaught ReferenceError: Provider is not defined
>     at Object.<anonymous> (bundle.js:86)
>     at __webpack_require__ (bundle.js:20)
>     at Object.<anonymous> (bundle.js:47)
>     at __webpack_require__ (bundle.js:20)
>     at bundle.js:40
>     at bundle.js:43

Any ideas why this would be an issue?

Thanks!

**Comment by maximsan** [comment]
I've encountered another error with react-router **"Uncaught TypeError: Cannot read property 'func' of undefined"**. It was fixed by updating to **react-router@3.2.0** as for me. I'm not sure, but maybe it will fix your problem too.

**Comment by adharbert** [comment]
Thanks for the response, I tried that last night as well but still have the error.  I might blow the project away and start from scratch, it might be a bad download or something.

**Comment by nagarajach** [comment]
Please type this command in your command prompt
npm dist-tag ls react-router.

Will find this below output:
$ npm dist-tag ls react-router
latest: 4.1.1
next: 4.0.0
previous: 3.0.5
$ npm dist-tag ls react-router-dom
latest: 4.1.1
next: 4.0.0-beta.8
. So based on this we could install latest version like 
npm install --save react-router@4.1.1.

Might be with your issue will be resolved.

**Comment by David2913** [comment]
Also, you could consider installing react-router-dom instead of react-router, it seems to be the way to go regarding routing. I used only that dependency and did not encounter any problems

**Comment by shrimpdoom1920** [comment]
Thanks @maximsan for sharing this. I thought that I would never finish this course because of this stupid bug.
